version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
        environment:
          - CHROME_BIN: /usr/bin/google-chrome
          - DISPLAY: ":99.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install selenium-webdriver chromedriver
      - run:
          name: Run tests
          command: node Test.js
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  example:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
