version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14  # Use the same image for consistency
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/node:16.14  # Use the same image for consistency
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy
          command: echo "Deployment script goes here"

workflows:
  example:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master




